version: "3"
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "4000:5432"
    networks:
      - "lambda-local"
volumes:
  database-data:
networks:
  lambda-local:
    external: true